In [192]:
import pandas as pd

# Leer el archivo
df_renta_ingresos = pd.read_csv('data/distribucion-renta-ingresos.csv')

# Ver las primeras filas
# print(df_renta_ingresos.head())

# df_renta_ingresos['MEDIDAS_CODE'].unique()

provincias_detectadas = df_renta_ingresos['TERRITORIO_CODE'].apply(lambda x: x.split('_')[1][:2]).unique()

registros_provincia_38 = df_renta_ingresos[
    df_renta_ingresos['TERRITORIO_CODE'].apply(lambda x: x.split('_')[1][:2]) == '38'
]

# print("--- Nulos en Distribución de Ingresos ---")
# print(registros_provincia_38.isna().sum())

print(registros_provincia_38.isna().sum())
print(registros_provincia_38.dtypes)

año                0
distrito           0
MEDIDAS_CODE       0
MEDIDAS#es         0
municipio          0
OBS_VALUE          0
seccion            0
TERRITORIO_CODE    0
dtype: int64
año                int64
distrito           int64
MEDIDAS_CODE         str
MEDIDAS#es           str
municipio            str
OBS_VALUE            str
seccion            int64
TERRITORIO_CODE      str
dtype: object

In [193]:
# Leer el archivo
df_renta_ingresos_clean = pd.read_csv('data/distribucion-renta-ingresos-clean.csv')

print(df_renta_ingresos_clean.isna().sum())
print(df_renta_ingresos_clean.dtypes)
print(df_renta_ingresos_clean['MEDIDAS'].unique())

# Ver las primeras filas
df_renta_ingresos_clean.head()

año             0
MEDIDAS_CODE    0
MEDIDAS         0
municipio       0
OBS_VALUE       0
geocode         0
dtype: int64
año               int64
MEDIDAS_CODE        str
MEDIDAS             str
municipio           str
OBS_VALUE       float64
geocode             str
dtype: object
<StringArray>
[        'Otras prestaciones',             'Otros ingresos',
                  'Pensiones', 'Prestaciones por desempleo',
         'Sueldos y salarios']
Length: 5, dtype: str

,año,MEDIDAS_CODE,MEDIDAS,municipio,OBS_VALUE,geocode
0,2021,OTRAS_PRESTACIONES,Otras prestaciones,Adeje,1.9,20210101_38001_D01_S011
1,2021,OTRAS_PRESTACIONES,Otras prestaciones,Adeje,1.9,20210101_38001_D01_S018
2,2021,OTRAS_PRESTACIONES,Otras prestaciones,Adeje,2.4,20210101_38001_D01_S008
3,2021,OTRAS_PRESTACIONES,Otras prestaciones,Adeje,2.4,20210101_38001_D01_S009
4,2021,OTRAS_PRESTACIONES,Otras prestaciones,Adeje,2.5,20210101_38001_D01_S007

In [194]:
# Leer el archivo
df_rentamedia = pd.read_csv('data/rentamedia-sc-3.csv')

# Ver las primeras filas
print(df_rentamedia.head())

# df_rentamedia['MEDIDAS_CODE'].unique()

provincias_detectadas = df_rentamedia['TERRITORIO_CODE'].apply(lambda x: x.split('_')[1][:2]).unique()

registros_provincia_38 = df_rentamedia[
    df_rentamedia['TERRITORIO_CODE'].apply(lambda x: x.split('_')[1][:2]) == '38'
]

# print("--- Nulos en Distribución de Ingresos ---")
# print(registros_provincia_38.isna().sum())

print(registros_provincia_38.isna().sum())
print(registros_provincia_38.dtypes)

    año             MEDIDAS_CODE                   MEDIDAS#es  \
0  2021  RENTA_BRUTA_MEDIA_HOGAR  Renta bruta media por hogar
1  2021  RENTA_BRUTA_MEDIA_HOGAR  Renta bruta media por hogar
2  2021  RENTA_BRUTA_MEDIA_HOGAR  Renta bruta media por hogar
3  2021  RENTA_BRUTA_MEDIA_HOGAR  Renta bruta media por hogar
4  2021  RENTA_BRUTA_MEDIA_HOGAR  Renta bruta media por hogar

           TERRITORIO_CODE  distrito  seccion municipio  OBS_VALUE
0  20220101_38001_D01_S001         1        1     Adeje    31387.0
1  20220101_38001_D01_S002         1        2     Adeje    28541.0
2  20220101_38001_D01_S003         1        3     Adeje    33268.0
3  20220101_38001_D01_S004         1        4     Adeje    27259.0
4  20220101_38001_D01_S005         1        5     Adeje    34744.0
año                 0
MEDIDAS_CODE        0
MEDIDAS#es          0
TERRITORIO_CODE     0
distrito            0
seccion             0
municipio           0
OBS_VALUE          30
dtype: int64
año                  int64
MEDIDAS_CODE           str
MEDIDAS#es             str
TERRITORIO_CODE        str
distrito             int64
seccion              int64
municipio              str
OBS_VALUE          float64
dtype: object

In [195]:
filas_con_nulos = df_rentamedia[df_rentamedia.isnull().any(axis=1)]
filas_con_nulos

,año,MEDIDAS_CODE,MEDIDAS#es,TERRITORIO_CODE,distrito,seccion,municipio,OBS_VALUE
130,2021,RENTA_BRUTA_MEDIA_HOGAR,Renta bruta media por hogar,20220101_38017_D01_S026,1,26,Granadilla de Abona,NaN
155,2021,RENTA_BRUTA_MEDIA_HOGAR,Renta bruta media por hogar,20220101_38020_D01_S012,1,12,Güímar,NaN
263,2021,RENTA_BRUTA_MEDIA_HOGAR,Renta bruta media por hogar,20220101_38023_D03_S027,3,27,San Cristóbal de La Laguna,NaN
264,2021,RENTA_BRUTA_MEDIA_HOGAR,Renta bruta media por hogar,20220101_38023_D03_S028,3,28,San Cristóbal de La Laguna,NaN
265,2021,RENTA_BRUTA_MEDIA_HOGAR,Renta bruta media por hogar,20220101_38023_D03_S029,3,29,San Cristóbal de La Laguna,NaN
807,2021,RENTA_BRUTA_MEDIA_PERSONA,Renta bruta media por persona,20220101_38017_D01_S026,1,26,Granadilla de Abona,NaN
832,2021,RENTA_BRUTA_MEDIA_PERSONA,Renta bruta media por persona,20220101_38020_D01_S012,1,12,Güímar,NaN
940,2021,RENTA_BRUTA_MEDIA_PERSONA,Renta bruta media por persona,20220101_38023_D03_S027,3,27,San Cristóbal de La Laguna,NaN
941,2021,RENTA_BRUTA_MEDIA_PERSONA,Renta bruta media por persona,20220101_38023_D03_S028,3,28,San Cristóbal de La Laguna,NaN
942,2021,RENTA_BRUTA_MEDIA_PERSONA,Renta bruta media por persona,20220101_38023_D03_S029,3,29,San Cristóbal de La Laguna,NaN
1484,2021,RENTA_NETA_MEDIA_HOGAR,Renta neta media por hogar,20220101_38017_D01_S026,1,26,Granadilla de Abona,NaN
1509,2021,RENTA_NETA_MEDIA_HOGAR,Renta neta media por hogar,20220101_38020_D01_S012,1,12,Güímar,NaN
1617,2021,RENTA_NETA_MEDIA_HOGAR,Renta neta media por hogar,20220101_38023_D03_S027,3,27,San Cristóbal de La Laguna,NaN
1618,2021,RENTA_NETA_MEDIA_HOGAR,Renta neta media por hogar,20220101_38023_D03_S028,3,28,San Cristóbal de La Laguna,NaN
1619,2021,RENTA_NETA_MEDIA_HOGAR,Renta neta media por hogar,20220101_38023_D03_S029,3,29,San Cristóbal de La Laguna,NaN
2161,2021,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20220101_38017_D01_S026,1,26,Granadilla de Abona,NaN
2186,2021,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20220101_38020_D01_S012,1,12,Güímar,NaN
2294,2021,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20220101_38023_D03_S027,3,27,San Cristóbal de La Laguna,NaN
2295,2021,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20220101_38023_D03_S028,3,28,San Cristóbal de La Laguna,NaN
2296,2021,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20220101_38023_D03_S029,3,29,San Cristóbal de La Laguna,NaN
2838,2021,RENTA_NETA_UNIDAD_CONSUMO_MEDIA,Media de la renta por unidad de consumo,20220101_38017_D01_S026,1,26,Granadilla de Abona,NaN
2863,2021,RENTA_NETA_UNIDAD_CONSUMO_MEDIA,Media de la renta por unidad de consumo,20220101_38020_D01_S012,1,12,Güímar,NaN
2971,2021,RENTA_NETA_UNIDAD_CONSUMO_MEDIA,Media de la renta por unidad de consumo,20220101_38023_D03_S027,3,27,San Cristóbal de La Laguna,NaN
2972,2021,RENTA_NETA_UNIDAD_CONSUMO_MEDIA,Media de la renta por unidad de consumo,20220101_38023_D03_S028,3,28,San Cristóbal de La Laguna,NaN
2973,2021,RENTA_NETA_UNIDAD_CONSUMO_MEDIA,Media de la renta por unidad de consumo,20220101_38023_D03_S029,3,29,San Cristóbal de La Laguna,NaN
3515,2021,RENTA_NETA_UNIDAD_CONSUMO_MEDIANA,Mediana de la renta por unidad de consumo,20220101_38017_D01_S026,1,26,Granadilla de Abona,NaN
3540,2021,RENTA_NETA_UNIDAD_CONSUMO_MEDIANA,Mediana de la renta por unidad de consumo,20220101_38020_D01_S012,1,12,Güímar,NaN
3648,2021,RENTA_NETA_UNIDAD_CONSUMO_MEDIANA,Mediana de la renta por unidad de consumo,20220101_38023_D03_S027,3,27,San Cristóbal de La Laguna,NaN
3649,2021,RENTA_NETA_UNIDAD_CONSUMO_MEDIANA,Mediana de la renta por unidad de consumo,20220101_38023_D03_S028,3,28,San Cristóbal de La Laguna,NaN
3650,2021,RENTA_NETA_UNIDAD_CONSUMO_MEDIANA,Mediana de la renta por unidad de consumo,20220101_38023_D03_S029,3,29,San Cristóbal de La Laguna,NaN

In [202]:
# Leer el archivo
df_rentamedia_clean = pd.read_csv('data/rentamedia-sc-3-clean.csv')

# Ver las primeras filas
filas_con_nulos2 = df_rentamedia_clean[df_rentamedia_clean.isnull().any(axis=1)]
print(len(filas_con_nulos2))

print(df_rentamedia_clean.isna().sum())
print(df_rentamedia_clean.dtypes)
print(df_rentamedia_clean['MEDIDAS'].unique())
df_grafico2 = df_rentamedia_clean[(df_rentamedia_clean['MEDIDAS'] == 'Renta neta media por persona') & (df_rentamedia_clean['año'] == 2023)]
          
df_grafico2
# df_rentamedia_clean.head()

0
año             0
MEDIDAS_CODE    0
MEDIDAS         0
geocode         0
municipio       0
OBS_VALUE       0
dtype: int64
año               int64
MEDIDAS_CODE        str
MEDIDAS             str
geocode             str
municipio           str
OBS_VALUE       float64
dtype: object
<StringArray>
[              'Renta bruta media por hogar',
             'Renta bruta media por persona',
                'Renta neta media por hogar',
              'Renta neta media por persona',
   'Media de la renta por unidad de consumo',
 'Mediana de la renta por unidad de consumo']
Length: 6, dtype: str

,año,MEDIDAS_CODE,MEDIDAS,geocode,municipio,OBS_VALUE
10191,2023,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20230101_38001_D01_S001,Adeje,12571.0
10192,2023,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20230101_38001_D01_S002,Adeje,10894.0
10193,2023,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20230101_38001_D01_S003,Adeje,13643.0
10194,2023,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20230101_38001_D01_S004,Adeje,10939.0
10195,2023,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20230101_38001_D01_S005,Adeje,12018.0
...,...,...,...,...,...,...
10867,2023,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20230101_38053_D01_S002,Villa de Mazo,13099.0
10868,2023,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20230101_38053_D01_S003,Villa de Mazo,14419.0
10869,2023,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20230101_38053_D01_S004,Villa de Mazo,12771.0
10870,2023,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20230101_38053_D01_S005,Villa de Mazo,12497.0
10871,2023,RENTA_NETA_MEDIA_PERSONA,Renta neta media por persona,20230101_38901_D01_S001,El Pinar de El Hierro,13089.0

In [214]:
import geopandas as gpd

df_grafico2['geocode'] = '2024' + df_grafico2['geocode'].str[4:]

gdf_tenerife_2023 = gpd.read_file('data/secciones_20240101_tenerife.json')
gdf_tenerife_2023['geocode'].dtype

gdf_final_map = pd.merge(gdf_tenerife_2023, df_grafico2, on='geocode', how='left')

gdf_final_map.dtypes

nulos_renta_raw = gdf_final_map['OBS_VALUE'].isna().sum()
total_secciones_raw = len(gdf_final_map)
    
    # 2. CASTEO ESTRICTO A TIPOS NATIVOS DE PYTHON (Para contentar a Dagster)
nulos_renta = int(nulos_renta_raw)
total_secciones = int(total_secciones_raw)
    
    # 3. Cálculo de la tasa de cobertura
if total_secciones == 0:
    tasa_cobertura = 0.0
else:
    tasa_cobertura = (total_secciones - nulos_renta) / total_secciones

tasa_cobertura

passed = tasa_cobertura >= 0.90

passed

True

In [186]:
# Leer el archivo
df_ocupacion = pd.read_csv('data/ocupacion-sc-3.csv')

print("--- Nulos en Ocupación ---")
print(df_ocupacion.isna().sum())
print(df_ocupacion.dtypes)
print(len(df_ocupacion))

# Ver las primeras filas
df_ocupacion.head()

--- Nulos en Ocupación ---
ocupacion         0
code_municipio    0
code_distrito     0
code_seccion      0
año               0
municipio         0
seccion           0
sexo              0
num_casos         0
geocode           0
dtype: int64
ocupacion           str
code_municipio    int64
code_distrito     int64
code_seccion      int64
año               int64
municipio           str
seccion           int64
sexo                str
num_casos         int64
geocode             str
dtype: object
16240

,ocupacion,code_municipio,code_distrito,code_seccion,año,municipio,seccion,sexo,num_casos,geocode
0,Directores/gerentes y profesionales/técnicos d...,38001,1,1,2021,Adeje,1001,Hombres,74,20210101_38001_D01_S001
1,Directores/gerentes y profesionales/técnicos d...,38001,1,1,2021,Adeje,1001,Mujeres,78,20210101_38001_D01_S001
2,Directores/gerentes y profesionales/técnicos d...,38001,1,1,2022,Adeje,1001,Hombres,88,20220101_38001_D01_S001
3,Directores/gerentes y profesionales/técnicos d...,38001,1,1,2022,Adeje,1001,Mujeres,84,20220101_38001_D01_S001
4,Directores/gerentes y profesionales/técnicos d...,38001,1,1,2023,Adeje,1001,Hombres,88,20230101_38001_D01_S001

In [187]:
df_ocupacion

,ocupacion,code_municipio,code_distrito,code_seccion,año,municipio,seccion,sexo,num_casos,geocode
0,Directores/gerentes y profesionales/técnicos d...,38001,1,1,2021,Adeje,1001,Hombres,74,20210101_38001_D01_S001
1,Directores/gerentes y profesionales/técnicos d...,38001,1,1,2021,Adeje,1001,Mujeres,78,20210101_38001_D01_S001
2,Directores/gerentes y profesionales/técnicos d...,38001,1,1,2022,Adeje,1001,Hombres,88,20220101_38001_D01_S001
3,Directores/gerentes y profesionales/técnicos d...,38001,1,1,2022,Adeje,1001,Mujeres,84,20220101_38001_D01_S001
4,Directores/gerentes y profesionales/técnicos d...,38001,1,1,2023,Adeje,1001,Hombres,88,20230101_38001_D01_S001
...,...,...,...,...,...,...,...,...,...,...
16235,Trabajadores cualificados y oficiales/operario...,38901,1,1,2021,"Pinar de El Hierro, El",1001,Mujeres,165,20210101_38901_D01_S001
16236,Trabajadores cualificados y oficiales/operario...,38901,1,1,2022,"Pinar de El Hierro, El",1001,Hombres,225,20220101_38901_D01_S001
16237,Trabajadores cualificados y oficiales/operario...,38901,1,1,2022,"Pinar de El Hierro, El",1001,Mujeres,158,20220101_38901_D01_S001
16238,Trabajadores cualificados y oficiales/operario...,38901,1,1,2023,"Pinar de El Hierro, El",1001,Hombres,227,20230101_38901_D01_S001
16239,Trabajadores cualificados y oficiales/operario...,38901,1,1,2023,"Pinar de El Hierro, El",1001,Mujeres,177,20230101_38901_D01_S001

In [188]:
df_ocupacion_clean = pd.read_csv('data/ocupacion-sc-3-clean.csv')

print(df_ocupacion_clean['ocupacion'].unique())
print(df_ocupacion_clean.dtypes)
print(len(df_ocupacion_clean))

# Ver las primeras filas
df_ocupacion_clean.head()

<StringArray>
['Directores/gerentes y profesionales/técnicos de nivel medio o alto',
                                                          'No consta',
                                            'Ocupaciones elementales',
      'Trabajadores cualificados y oficiales/operarios de nivel bajo']
Length: 4, dtype: str
año          int64
municipio      str
geocode        str
ocupacion      str
num_casos    int64
dtype: object
8120

,año,municipio,geocode,ocupacion,num_casos
0,2021,Adeje,20210101_38001_D01_S001,Directores/gerentes y profesionales/técnicos d...,152
1,2021,Adeje,20210101_38001_D01_S001,No consta,27
2,2021,Adeje,20210101_38001_D01_S001,Ocupaciones elementales,104
3,2021,Adeje,20210101_38001_D01_S001,Trabajadores cualificados y oficiales/operario...,372
4,2021,Adeje,20210101_38001_D01_S002,Directores/gerentes y profesionales/técnicos d...,161

In [189]:
# Leer el archivo
df_actividad = pd.read_csv('data/actividad-sc-3.csv')
df_actividad_clean = pd.read_csv('data/actividad-sc-3-clean.csv')

print(len(df_actividad))
print(df_actividad.isna().sum())
print(df_actividad.dtypes)

# Ver las primeras filas
df_actividad.head()

# print("--- Nulos en Actividad ---")
# print(df_actividad.isna().sum())

# df_actividad['provincia'].unique()

20460
Actividad económica      0
cod_municipio            0
cod_provincia            0
geocode                  0
municipio                0
num_casos              163
Periodo                  0
provincia                0
Sexo                     0
dtype: int64
Actividad económica        str
cod_municipio            int64
cod_provincia            int64
geocode                    str
municipio                  str
num_casos              float64
Periodo                  int64
provincia                  str
Sexo                       str
dtype: object

,Actividad económica,cod_municipio,cod_provincia,geocode,municipio,num_casos,Periodo,provincia,Sexo
0,"Agricultura, ganadería y pesca",38001,38,20210101_38001_D01_S001,Adeje,NaN,2021,Santa Cruz de Tenerife,Hombres
1,"Agricultura, ganadería y pesca",38001,38,20210101_38001_D01_S001,Adeje,2.0,2021,Santa Cruz de Tenerife,Mujeres
2,"Agricultura, ganadería y pesca",38001,38,20210101_38001_D01_S002,Adeje,5.0,2021,Santa Cruz de Tenerife,Mujeres
3,"Agricultura, ganadería y pesca",38001,38,20210101_38001_D01_S002,Adeje,8.0,2021,Santa Cruz de Tenerife,Hombres
4,"Agricultura, ganadería y pesca",38001,38,20210101_38001_D01_S003,Adeje,4.0,2021,Santa Cruz de Tenerife,Mujeres

In [190]:
print(len(df_actividad_clean))
print(df_actividad_clean['Actividad económica'].unique())
print(df_actividad_clean.isna().sum())
print(df_actividad_clean.dtypes)

# Ver las primeras filas
df_actividad_clean.head()

10230
<StringArray>
['Agricultura, ganadería y pesca',                   'Construcción',
                      'Industria',                      'No consta',
                      'Servicios']
Length: 5, dtype: str
año                    0
municipio              0
geocode                0
Actividad económica    0
num_casos              0
dtype: int64
año                    int64
municipio                str
geocode                  str
Actividad económica      str
num_casos              int64
dtype: object

,año,municipio,geocode,Actividad económica,num_casos
0,2021,Adeje,20210101_38001_D01_S001,"Agricultura, ganadería y pesca",2
1,2021,Adeje,20210101_38001_D01_S001,Construcción,40
2,2021,Adeje,20210101_38001_D01_S001,Industria,21
3,2021,Adeje,20210101_38001_D01_S001,No consta,0
4,2021,Adeje,20210101_38001_D01_S001,Servicios,591

In [191]:
print(len(df_renta_ingresos_clean))
print(len(df_rentamedia_clean))

10195
12234

In [155]:
df_master = pd.read_csv('data/df_master.csv')

df_master.head()

,año,TERRITORIO_CODE,municipio,renta_media_hogar,OTRAS_PRESTACIONES,PENSIONES,PRESTACIONES_DESEMPLEO,SUELDOS_SALARIOS,Directores/gerentes y profesionales/técnicos de nivel medio o alto,No consta_x,Ocupaciones elementales,Trabajadores cualificados y oficiales/operarios de nivel bajo,"Agricultura, ganadería y pesca",Construcción,Industria,No consta_y,Servicios
0,2021,20210101_38001_D01_S001,Adeje,31387.0,3.5,14.9,11.6,54.2,152.0,27.0,104.0,372.0,2.0,40.0,21.0,0.0,591.0
1,2021,20210101_38001_D01_S002,Adeje,28541.0,4.6,13.5,16.6,58.4,161.0,40.0,197.0,618.0,13.0,39.0,22.0,0.0,942.0
2,2021,20210101_38001_D01_S003,Adeje,33268.0,3.0,11.4,13.4,51.0,194.0,37.0,135.0,699.0,14.0,39.0,18.0,1.0,993.0
3,2021,20210101_38001_D01_S004,Adeje,27259.0,4.8,17.3,13.7,54.2,105.0,29.0,192.0,452.0,31.0,37.0,28.0,0.0,682.0
4,2021,20210101_38001_D01_S005,Adeje,34744.0,3.3,18.1,10.8,53.2,203.0,32.0,198.0,571.0,47.0,58.0,39.0,0.0,860.0

In [159]:
filas_con_nulos2 = df_actividad[df_actividad.isnull().any(axis=1)]
filas_con_nulos2

,Actividad económica,cod_municipio,cod_provincia,geocode,municipio,num_casos,Periodo,provincia,Sexo
0,"Agricultura, ganadería y pesca",38001,38,20210101_38001_D01_S001,Adeje,NaN,2021,Santa Cruz de Tenerife,Hombres
36,"Agricultura, ganadería y pesca",38001,38,20220101_38001_D01_S001,Adeje,NaN,2022,Santa Cruz de Tenerife,Hombres
72,"Agricultura, ganadería y pesca",38001,38,20230101_38001_D01_S001,Adeje,NaN,2023,Santa Cruz de Tenerife,Hombres
388,"Agricultura, ganadería y pesca",38007,38,20230101_38007_D01_S002,Barlovento,NaN,2023,Santa Cruz de Tenerife,Hombres
389,"Agricultura, ganadería y pesca",38007,38,20230101_38007_D01_S002,Barlovento,NaN,2023,Santa Cruz de Tenerife,Mujeres
...,...,...,...,...,...,...,...,...,...
18939,Servicios,38036,38,20220101_38036_D01_S008,San Sebastián de la Gomera,NaN,2022,Santa Cruz de Tenerife,Mujeres
19104,Servicios,38038,38,20210101_38038_D03_S021,Santa Cruz de Tenerife,NaN,2021,Santa Cruz de Tenerife,Hombres
19105,Servicios,38038,38,20210101_38038_D03_S021,Santa Cruz de Tenerife,NaN,2021,Santa Cruz de Tenerife,Mujeres
19434,Servicios,38038,38,20220101_38038_D03_S021,Santa Cruz de Tenerife,NaN,2022,Santa Cruz de Tenerife,Hombres
19435,Servicios,38038,38,20220101_38038_D03_S021,Santa Cruz de Tenerife,NaN,2022,Santa Cruz de Tenerife,Mujeres

In [162]:
len(df_actividad[df_actividad['num_casos'] == 0])

4298

In [163]:
len(df_actividad)

20460

In [216]:
df_municipio_sector = (
    df_actividad_clean.groupby(['municipio', 'Actividad económica'], as_index=False)
    ['num_casos'].sum()
)

# 3. Encontrar la fila con el máximo número de casos para cada municipio
# idxmax() identifica el índice del valor más alto dentro de cada grupo de municipios
idx_maximo = df_municipio_sector.groupby('municipio')['num_casos'].idxmax()
df_sector_mayoritario = df_municipio_sector.loc[idx_maximo].copy()

# 4. Ordenar el resultado por volumen para facilitar el análisis visual
df_sector_mayoritario = df_sector_mayoritario.sort_values(by='num_casos', ascending=False)

# Mostrar el resultado
print(df_sector_mayoritario.to_string(index=False))
print(df_sector_mayoritario['Actividad económica'].unique())

                 municipio Actividad económica  num_casos
    Santa Cruz de Tenerife           Servicios     220109
San Cristóbal de La Laguna           Servicios     168609
                     Arona           Servicios      85988
       Granadilla de Abona           Servicios      56561
                     Adeje           Servicios      54380
               Orotava, La           Servicios      41636
             Realejos, Los           Servicios      35775
                Candelaria           Servicios      32313
         Puerto de la Cruz           Servicios      28276
                 Tacoronte           Servicios      24781
       San Miguel de Abona           Servicios      23564
             Guía de Isora           Servicios      21661
                    Güímar           Servicios      21242
               Rosario, El           Servicios      20842
         Icod de los Vinos           Servicios      19756
    Llanos de Aridane, Los           Servicios      19521
    Santa Cruz de la Palma           Servicios      15950
              Santa Úrsula           Servicios      15349
                  Tegueste           Servicios      12791
        Santiago del Teide           Servicios      10735
San Sebastián de la Gomera           Servicios      10484
                Sauzal, El           Servicios       9026
   Matanza de Acentejo, La           Servicios       8969
  Victoria de Acentejo, La           Servicios       8267
                Breña Alta           Servicios       7825
                     Arico           Servicios       7665
                  Paso, El           Servicios       7181
                Breña Baja           Servicios       6676
                     Arafo           Servicios       5750
                  Valverde           Servicios       5221
               Guancha, La           Servicios       4918
             Villa de Mazo           Servicios       4713
     San Juan de la Rambla           Servicios       4401
            Valle Gran Rey           Servicios       4389
       San Andrés y Sauces           Servicios       3970
                 Garachico           Servicios       3938
                  Frontera           Servicios       3797
                 Tazacorte           Servicios       3772
      Buenavista del Norte           Servicios       3739
                Silos, Los           Servicios       3411
                    Fasnia           Servicios       2767
                Puntallana           Servicios       2358
                Tanque, El           Servicios       2294
              Vallehermoso           Servicios       2230
                   Alajeró           Servicios       2200
                  Tijarafe           Servicios       2058
        Vilaflor de Chasna           Servicios       1828
    Pinar de El Hierro, El           Servicios       1711
  Fuencaliente de la Palma           Servicios       1662
                  Hermigua           Servicios       1601
                Barlovento           Servicios       1592
                Puntagorda           Servicios       1592
                   Garafía           Servicios       1128
                     Agulo           Servicios        947
<StringArray>
['Servicios']
Length: 1, dtype: str